name: Update Status

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'Set the On/Off Air status'
        required: true
        default: 'off-air'

jobs:
  update_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check out the current status.json
        run: cat status.json  # Print the status.json to see its current content

      - name: Set up GitHub token
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update Status in status.json
        run: |
          echo "Updating status file..."
          STATUS="${{ github.event.inputs.status }}"  # Use input passed from the frontend

          # Modify the status file
          echo "{
            \"status\": \"${STATUS}\",
            \"last_updated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
          }" > status.json

          cat status.json  # Show the contents of the updated file before commit

      - name: Commit and push the status update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add status.json
          git commit -m "Update status to ${STATUS}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.RADIO }}  # Use your GitHub secret token here

      - name: Debugging - Check push result
        run: |
          echo "Git push attempt finished."
